language: python
services:
    - postgresql
addons:
    hosts:
        - db
env:
    - TRAVIS=true
python:
  - "3.5"
install:
  - sudo mkdir /usr/local/demotime
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
  - pip install -r prod_requirements.txt
  - export PYTHONPATH=$PYTHONPATH:`pwd`/demotime
script:
  - invoke run_tests
notifications:
  email:
    recipients:
      - f4nt@f4ntasmic.com
