sudo: required
language: node_js
node_js:
    - 0.12.7
services:
    - docker
addons:
    hosts:
        - db
env:
    - DOCKER_COMPOSE_VERSION=1.7.0
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker volume create --name dt_pg_data
  - docker volume create --name dt_static_data
  - docker volume create --name dt_rmq_data
script:
    - npm test
    - rm -rf node_modules
    - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d
    - docker exec -it demotime_demotime_1 /bin/bash -c "cd ../ && invoke run_tests"
    - docker exec -i src_demotime_1 /bin/bash -c "/bin/bash <(curl -s https://codecov.io/bash)"
    - docker-compose -f docker-compose.yml -f docker-compose.build.yml down
after_success:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push domestique/demotime;
      else
        docker tag domestique/demotime:latest domestique/demotime:${TRAVIS_BRANCH};
        docker push domestique/demotime:${TRAVIS_BRANCH};
      fi
notifications:
  email:
    recipients:
      - f4nt@f4ntasmic.com
      - dannypeck@gmail.com
