version: '2'
services: 
    db:
        image: postgres:latest
        ports:
            - "5432:55432"
    demotime:
        build: .
        image: xxf4ntxx/demotime
        command: cd ../ && invoke run_tests
        volumes:
            - .:/home/docker/demotime
