version: '2'
volumes:
    dt_pg_data:
        external: true
    dt_static_data:
        external: true
    dt_rmq_data:
        external: true
services: 
    rmq:
        image: rabbitmq:3.6.2
        environment:
            - RABBITMQ_DEFAULT_USER=demotime
            - RABBITMQ_DEFAULT_PASS=demotime
            - RABBITMQ_DEFAULT_VHOST=demotime
        volumes:
            - dt_rmq_data:/var/lib/rabbitmq
    db:
        image: postgres:9.5.3
        environment:
            - POSTGRES_PASSWORD=demotime_docker
        volumes:
            - dt_pg_data:/var/lib/postgresql/data
            - ~/dt_backups:/backups
    demotime:
        command: ./startup.sh
        depends_on:
            - db
            - rmq
        volumes:
            - dt_static_data:/usr/local/demotime
            - /etc/demotime:/etc/demotime
            - ~/dt_backups:/backups
        ports:
            - "8033:8033"
        links:
            - db
            - rmq
        environment:
            - STATIC_PATH=/usr/local/demotime/static/
    demotime_celery:
        command: ./start_celery.sh
        depends_on:
            - db
            - rmq
        volumes:
            - /etc/demotime:/etc/demotime
        links:
            - db
            - rmq
