version: '2'
services: 
    db:
        image: postgres:latest
        ports:
            - "5432:55432"
    demotime:
        build: .
        command: ./startup.sh
        volumes:
            - .:/home/docker/demotime
        ports:
            - "8000:8000"
