version: '2'
services: 
    db:
        image: postgres:latest
    demotime:
        build: .
        command: ./startup.sh
        volumes:
            - .:/home/docker/demotime
        ports:
            - "8000:8000"
        depends_on:
            - db
