version: '2'
volumes:
    dt_pg_data:
        external: true
    dt_static_data:
        external: true
services: 
    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=demotime_docker
        volumes:
            - dt_pg_data:/var/lib/postgresql/data
            - /tmp:/tmp/host_tmp
    demotime:
        command: ./startup.sh
        depends_on:
            - db
        volumes:
            - dt_static_data:/usr/local/demotime
            - /etc/demotime:/etc/demotime
        ports:
            - "8000:8000"
