version: '2'
services: 
    db:
        image: postgres:latest
    demotime:
        image: xxf4ntxx/demotime:latest
        command: ./startup.sh
        volumes:
            - .:/home/docker/demotime
        ports:
            - "8000:8000"
        depends_on:
            - db
