version: '2'
services: 
    db:
        image: postgres:latest
        ports:
            - "5432:55432"
    demotime:
        build: .
        image: domestique/demotime
        command: ./startup.sh
        volumes:
            - .:/home/docker/demotime
        environment:
            - STATIC_PATH=/home/docker/demotime/demotime/demotime/static
