# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0016_auto_20150503_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrevision',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
