# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0018_auto_20160326_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrevision',
            name='number',
            field=models.IntegerField(),
        ),
    ]
