# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_message_bundles(apps, schema_editor):
    Message = apps.get_model('demotime', 'Message')
    MessageBundle = apps.get_model('demotime', 'MessageBundle')
    User = apps.get_model('auth', 'User')

    unbundled_odd_messages = Message.objects.filter(review__isnull=True)
    assert not unbundled_odd_messages.filter(deleted=False).exists()
    print "Deleting {} unbundleable messages".format(
        unbundled_odd_messages.count()
    )
    unbundled_odd_messages.delete()

    for user in User.objects.all():
        for msg in user.receipient.filter(review__isnull=False):
            if msg.bundle or not msg.review:
                print "skipping bundling: {} or {}".format(msg.bundle, msg.review)
                continue

            bundle, _ = MessageBundle.objects.get_or_create(
                review=msg.review.review, # its really a ReviewRevision
                owner=msg.receipient,
            )
            Message.objects.filter(
                review=msg.review,
                receipient=msg.receipient,
            ).update(bundle=bundle)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demotime', '0020_rename_photo_attachment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.Review')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.MessageBundle'),
        ),
        migrations.RunPython(create_message_bundles)
    ]
