# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0021_messagebundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AlterField(
            model_name='message',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demotime.MessageBundle'),
        ),
    ]
