# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0023_auto_20160401_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagebundle',
            options={'ordering': ['-modified']},
        ),
    ]
