# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demotime', '0024_auto_20160409_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='followers',
            field=models.ManyToManyField(related_name='followers', through='demotime.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
