# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0025_review_followers'),
        ('demotime', '0024_auto_20160412_2305'),
    ]

    operations = [
    ]
