# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 22:24
from __future__ import unicode_literals

from django.db import migrations


def create_projects_groups_group_types(apps, schema_editor):
    Project = apps.get_model('demotime', 'Project')
    ProjectGroup = apps.get_model('demotime', 'ProjectGroup')
    Group = apps.get_model('demotime', 'Group')
    GroupMember = apps.get_model('demotime', 'GroupMember')
    GroupType = apps.get_model('demotime', 'GroupType')
    Review = apps.get_model('demotime', 'Review')
    User = apps.get_model('auth', 'User')

    default_project = Project.objects.create(
        name='Default Project',
        slug='default-project',
        description='Default DemoTime Project'
    )
    default_group_type = GroupType.objects.create(
        name='Default Group Type',
        slug='default-group-type',
    )
    default_group = Group.objects.create(
        name='Default Group',
        slug='default-group',
        description='Default DemoTime Group',
        group_type=default_group_type
    )
    user_list = User.objects.exclude(username='demotime_sys')
    for user in user_list:
        GroupMember.objects.create(
            user=user,
            group=default_group,
            is_admin=True,
        )

    ProjectGroup.objects.create(
        project=default_project,
        group=default_group,
        is_admin=True,
    )

    for review in Review.objects.all():
        review.project = default_project
        review.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0027_auto_20160424_2224'),
    ]

    operations = [
        migrations.RunPython(create_projects_groups_group_types)
    ]
