# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0031_generate_project_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='trigger_event',
            field=models.CharField(choices=[('created', 'Demo Created'), ('closed', 'Demo Closed'), ('aborted', 'Demo Aborted'), ('comment', 'Comment Added'), ('updated', 'Demo Updated'), ('reopened', 'Demo Reopened'), ('approved', 'Demo Approved'), ('rejected', 'Demo Rejected')], db_index=True, max_length=64),
        ),
    ]
