# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0035_create_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='setting',
            index_together=set([('project', 'key')]),
        ),
    ]
