# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 23:33
from __future__ import unicode_literals
from django.contrib.contenttypes.management import update_contenttypes

from django.db import migrations


def set_attachment_sort_order(apps, schema_editor):
    Review = apps.get_model('demotime', 'Review')
    Attachment = apps.get_model('demotime', 'Attachment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    app = apps.get_app_config('demotime')
    app.models_module = app.models_module or True
    update_contenttypes(app)
    content_type = ContentType.objects.get(
        model='reviewrevision',
        app_label='demotime'
    )
    for review in Review.objects.all():
        for revision in review.reviewrevision_set.all():
            attachments = Attachment.objects.filter(
                content_type=content_type,
                object_id=revision.pk
            ).order_by('pk')
            for count, attachment in enumerate(attachments, start=1):
                attachment.sort_order = count
                attachment.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('demotime', '0037_auto_20160823_1755'),
    ]

    operations = [
        migrations.RunPython(set_attachment_sort_order)
    ]
