# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 00:33
from __future__ import unicode_literals

from django.db import migrations


EVENT_TYPES = (
    ('Demo Created', 'demo-created'),
    ('Revision Added', 'revision-added'),
    ('Comment Added', 'comment-added'),
    ('Reviewer Approved', 'reviewer-approved'),
    ('Reviewer Rejected', 'reviewer-rejected'),
    ('Reviewer Reset', 'reviewer-reset'),
    ('Demo Opened', 'demo-opened'),
    ('Demo Closed', 'demo-closed'),
    ('Demo Aborted', 'demo-aborted'),
    ('Reviewer Added', 'reviewer-added'),
    ('Reviewer Removed', 'reviewer-removed'),
    ('Follower Added', 'follower-added'),
    ('Follower Removed', 'follower-removed')
)


def add_event_types(apps, schema_editor):
    EventType = apps.get_model('demotime', 'EventType')
    for name, code in EVENT_TYPES:
        EventType.objects.create(name=name, code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0037_auto_20160824_1933'),
    ]

    operations = [
        migrations.RunPython(add_event_types)
    ]
