# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0038_set_attachment_sort_order'),
        ('demotime', '0038_add_event_types'),
    ]

    operations = [
    ]
