# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demotime', '0039_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demotime.Review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='demotime.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='related_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('follower', 'Follower'), ('review', 'Review'), ('reviewer', 'Reviewer'), ('revision', 'Revision')], max_length=64),
        ),
    ]
