# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0040_auto_20160904_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
