# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0041_auto_20160923_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=128),
        ),
    ]
