# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0042_auto_20161030_1437'),
        ('demotime', '0042_auto_20161030_1412'),
    ]

    operations = [
    ]
