# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0043_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentthread',
            name='review_item',
            field=models.BooleanField(default=False),
        ),
    ]
