# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0043_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='open', max_length=128),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='trigger_event',
            field=models.CharField(choices=[('created', 'Demo Created'), ('closed', 'Demo Closed'), ('aborted', 'Demo Aborted'), ('comment', 'Comment Added'), ('updated', 'Demo Updated'), ('reopened', 'Demo Reopened'), ('approved', 'Demo Approved'), ('rejected', 'Demo Rejected'), ('paused', 'Demo Paused')], db_index=True, max_length=64),
        ),
    ]
