# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 21:37
from __future__ import unicode_literals

from django.db import migrations


def add_demo_paused_event_type(apps, _):
    EventType = apps.get_model('demotime', 'EventType')
    EventType.objects.get_or_create(
        name='Demo Paused',
        code='demo-paused'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0044_auto_20161126_1537'),
    ]

    operations = [
        migrations.RunPython(add_demo_paused_event_type)
    ]
