# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-03 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0047_migrate_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creator',
        ),
    ]
