# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0048_remove_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('follower', 'Follower'), ('review', 'Review'), ('reviewer', 'Reviewer'), ('revision', 'Revision'), ('creator', 'Creator')], max_length=64),
        ),
    ]
