# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 03:04
from __future__ import unicode_literals

from django.db import migrations


def add_issue_event_types(apps, _):
    EventType = apps.get_model('demotime', 'EventType')
    EventType.objects.get_or_create(
        name='Issue Created',
        code='issue-created'
    )
    EventType.objects.get_or_create(
        name='Issue Resolved',
        code='issue-resolved'
    )



class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0050_auto_20161229_2057'),
    ]

    operations = [
        migrations.RunPython(add_issue_event_types)
    ]
