# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0051_add_issue_event_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('follower', 'Follower'), ('review', 'Review'), ('reviewer', 'Reviewer'), ('revision', 'Revision'), ('creator', 'Creator'), ('issue', 'Issue')], max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
