# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0052_auto_20170107_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='reviewer',
            name='last_viewed',
            field=models.DateTimeField(null=True),
        ),
    ]
