# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0053_auto_20170118_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='review',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='messagebundle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='messagebundle',
            name='review',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageBundle',
        ),
    ]
