# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demotime', '0054_auto_20170121_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.Attachment')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.Comment')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demotime.Project')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demotime.ReactionType'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demotime.Review'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demotime.ReviewRevision'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
