# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:59
from __future__ import unicode_literals

from django.db import migrations

REACTION_TYPES = (
    ('love', 'Love'),
    ('like', 'Like'),
    ('plus-one', '+1'),
    ('minus-one', '-1'),
)

def add_reaction_types(apps, _):
    ReactionType = apps.get_model('demotime', 'ReactionType')
    for code, name in REACTION_TYPES:
        ReactionType.objects.create(
            name=name,
            code=code
        )


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0055_auto_20170122_1359'),
    ]

    operations = [
        migrations.RunPython(add_reaction_types)
    ]
