# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotime', '0056_add_reaction_types'),
        ('demotime', '0055_project_is_active'),
    ]

    operations = [
    ]
